name: generated_locator
description: >
  A helper generator creates index files for generators,
  in order to generate file in another folder.
version: 1.1.0
homepage: https://github.com/dart-ecosystem/generated_locator.dart
author: Copydog <775150@qq.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  build: ^1.2.2
  glob: ^1.2.0

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
  build_runner: ^1.7.1
